### ISSUE TITLE
Cuda memory issue

### ISSUE THREAD

**Issue by ayeshamkzhh** [fangwei123456/Parametric-Leaky-Integrate-and-Fire-Spiking-Neuron#3]
Hi,

We have trained N-MNIST using this repository but for the DVS128Gesture dataset, the codes gives the following cuda memory error:

- RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 10.74 GiB total capacity; 9.36 GiB already allocated; 28.31 MiB free; 9.38 GiB reserved in total by PyTorch)

We are using the parameters given in this github respository for the DVS128Gesture dataset with train_val.py file. Is there any way of reducing the required memory size?

**Comment by ayeshamkzhh** [comment]
Issue resolved with smaller batch size

**Comment by fangwei123456** [comment]
Smaller T (but may decrease accuracy) and smaller batch_size can reduce memory cost.
